IEEE-NITK/HacktoberFest

Contributors/Yash.txt
I'm an NITKian doing my first code at github and its cool!
=> adds Yash

Contributors/MishalShah.txt
=> Add Mishal.txt

Contributors/khursheed_Ali.txt
=> adds khursheed_Ali.txt file

Contributors/Gurupungav.txt
Food is nice. Also, Text file added.
=> Adds: Gurupungav.txt

Contributors/nihalhaneef.txt
=> Nihal added

Contributors/aswinManoj.txt
=> adds aswin.txt

Contributors/Chenna Keshava B S.txt
=>  adds Chenna Keshava B S

Contributors/ManojYadav.txt
=> Add ManojYadav.txt file

Contributors/harimanas.txt
=> add a contributor

Searching_Algorithms/Linear_Search/README.md
This is the documentation for Linear Search
=> adds the documentation

Hello_World/hello-world.cpp
=> Hello world done :)

Contributors/gautam.txt
=> gautam.txt

Contributors/nishant.txt.txt
=> add a contributer

Hello_World/hello-world.java
This code prints Hello World on Java
=> adds HelloWorldJava

Sorting_Algorithms/Bubble_Sort/BubbleSort.cpp
Added code for Bubble Sort in C++
=> Added Bubble Sort

Sorting_Algorithms/bubble.cpp
=> adds bubble.cpp bubble sort file

Searching_Algorithms/binary.cpp
=> adds binary.cpp binary search file

Patternprinter.txt
prints a diamond pattern in a grid of nxn
=> pattern printer

hello_world_in_basic.txt
=> add hello world in basic

HolaMundo
=> Create Hola mundo

CSV_download.py
=> CSV file download

Bse.txt, bsort.txt, hellow.rb, sort_it.txt
added in GitHub/HacktoberFest
files on helloworld ruby
bubble sort
sorting algorithm
binary search
=> Added files on bubblesort,hello world ruby

helloworld-chaos.c
=> Added a dummy Linux kernel module.

Calculator/calculator.c
1. Added '/' operator in printf
2.Removed spaces between format specifiers in scanf
3.Changed format specifiers from %.11f to %.2f so that it can take 2 decimal places and shows answer accurate
=> Done many changes!
